### ISSUE TITLE
sound is missing

### ISSUE THREAD

**Issue by Kingdark1986** [raiguard/Factorio-Flib#13]
Hi,
I just updated my factorio to a newer version and when I try to start the game with this mod active (amongst others) I get this error message. Any suggestion how I can fix it?

Thanks!

edit:
Almost forgot to mention, I updated it to version 18.25. Before, I was using the 'normal' version... I had no problems then.

![aaaaaa](https://user-images.githubusercontent.com/7038486/85956539-a8626b80-b986-11ea-89d4-da9f6a9d1173.png)

**Comment by 0ptera** [comment]
Should be fixed by removing hard coded sound paths and inheriting sounds from parent styles.

**Comment by Kingdark1986** [comment]
Eh, sorry, but what? What am I supposed to do? Sorry, if this seems obvious to you...

**Comment by raiguard** [comment]
Oh, your don't need to do anything, it'll be fixed with the next version.

I would push the update right now, but my house may or may not be burning down at the moment. I have my PC but no peripherals.

**Comment by Kingdark1986** [comment]
Hey, are you okay? Did your house burn down or was that a metaphor? I really hope it was, because losing your home can't ever be fun! Please take care of yourself, should that really have happened!

Kingdark

**Comment by raiguard** [comment]
Oh, hey sorry, I actually released the patch a while ago.

My house is fine, the firefighters did an amazing job. It was quite scary, though!

For reference, there was a massive wildfire, burned over 20,000 acres. My house was right in the path of it, but they managed to fight it off, and saved every house except for one (which was abandoned anyway, so it wasn't that much of a loss).

**Comment by Kingdark1986** [comment]
Hey, unfortunately, whatever you did, still didn't work. Here's another screenshot.
![Aantekening 2020-07-06 111107](https://user-images.githubusercontent.com/7038486/86576756-74d0a400-bf79-11ea-9a5d-3a7b45a97bea.png)

**Comment by Kingdark1986** [comment]
Also, just to make entirely sure, this is the only mod that's active currently.
edit:
I tried removing it and redownloading it from scratch, just in case something went wrong, but that isn't it. Could it be the game version that's the culprit?

**Comment by 0ptera** [comment]
0.1.5 works fine with 0.18.34 and 0.18.35.
Please post factorio-current.log instead of pointless screenshots.

**Comment by raiguard** [comment]
I neglected to update the base mod dependency, so it's allowing you to load it on too old of a version. Please update to the latest version.

**Comment by raiguard** [comment]
As per your other issue, you are on 0.18.26. This is why you're having this crash. Please update to the latest version.

I will update the base mod version dependency for the next patch to prevent this.
