### ISSUE TITLE
bug still not fixed

### ISSUE THREAD

**Issue by Kingdark1986** [raiguard/Factorio-Flib#14]
Hi,
I'm sorry for double posting, but I'm not sure if you saw that I replied to the previous problem I reported.

When I enable the mod, I have the next problem, seen in the screenshot below. I thought it might be another mod making the problem, but I disabled all mods. Your mod is the only one that's active. I also deleted it and redownloaded it, to make sure that nothing went wrong when you made your fix.

I also deleted it manually, and then redownloaded the mod, just to make absolutely sure that I covered my bases. It still ends up with the same problem. I'm currently using factorio version 18.26.
p.s
If you already saw that I replied to my previous bug report, then I apologize for this one, I don't mean to spam or anything like that.

![bug factorio](https://user-images.githubusercontent.com/7038486/86581019-cc720e00-bf7f-11ea-9e17-372b44c7e17f.png)

**Comment by raiguard** [comment]
It's not working because you're using an out-of-date version of the game. Please update to the latest version. I will update the base mod version dependency for the next patch to prevent this.
