### ISSUE TITLE
Error: Path __flib__/event.lua does not match any enabled mod.

### ISSUE THREAD

**Issue by ickputzdirwech** [raiguard/Factorio-Flib#20]
When I pressed the continue button in the main menu I got this error:

`...Data/Roaming/Factorio/temp/currently-playing/control.lua:5: Path __flib__/event.lua does not match any enabled mod.
stack traceback:
	[C]: in function 'require'
	...Data/Roaming/Factorio/temp/currently-playing/control.lua:5: in main chunk`

I had no mods enabled at that time. The save game had the following mods however: flib, EditorExtensions, factoryplanner

**Comment by raiguard** [comment]
Yes, EE's testing scenario relies on flib. If you remove EE and flib, that scenario will break.
