### ISSUE TITLE
tab-and-content

### ISSUE THREAD

**Issue by hahoyer** [raiguard/Factorio-Flib#24]
How to use tabs using flib? Haven't found any docu or examples. Can someone help me?

**Comment by raiguard** [comment]
For the `gui` module, it is like this:
```lua
{type = "tabbed-pane", children = {
  {type = "tab-and-content", tab = {type = "tab", caption = "Foo"}, content = {type = "flow", children = whatever}}
}}
```

For the `gui-beta` module it is like this:
```lua
{type = "tabbed-pane", tabs = {
  {tab = {type = "tab", caption = "Foo"}, content = {type = "flow", children = "whatever"}}
}}
```

I highly recommend using `gui-beta`. Sometime soon I'll get around to writing documentation for it so people know that it exists.

**Comment by hahoyer** [comment]
Thank you, that helped a lot.
Would you mind including this example somewhere in the doc?
As for gui-beta, how do I use that without the doc? It seems that it is not done just by replacing the require-statement.
![image](https://user-images.githubusercontent.com/144392/103130735-39986d80-469e-11eb-82be-ea27d8ed921f.png)

**Comment by raiguard** [comment]
Right now you have to read the source code to figure it out. `gui.build()` is similar, except for the `tabs` subtable as mentioned earlier. There is also an `actions` table that replaces the `handlers` subtable, and `save_as` is replaced by `ref`.

The way that the event handling works is completely different as well. I will take some time today to write some documentation.
