### ISSUE TITLE
Inconsistent minute output in ticks_to_timestring

### ISSUE THREAD

**Issue by modo-lv** [raiguard/Factorio-Flib#26]
Trivially minor, but I noticed that during the first hour of gameplay, single-digit minutes are printed without `0` the prefix (unlike after that).

This should probably be `"%02d:%02d"`:
https://github.com/factoriolib/flib/blob/01f73fbda8764a6a9a385008c6e552ec7afdea89/misc.lua#L33

**Comment by raiguard** [comment]
This is intentional, but I will add an option to keep the leading zeroes.
