### ISSUE TITLE
table.map implementation does not match documentation

### ISSUE THREAD

**Issue by Zomis** [raiguard/Factorio-Flib#33]
In `table.map` it says:

> Calls `mapper(value, key, tbl)` on each element in the table, using the return as the new value for the key.
> (...)
> @tparam function mapper Takes in `value`, `key`, and `tbl` as parameters.

But the implementation does not match this:

https://github.com/factoriolib/flib/blob/master/table.lua#L277

`output[k] = mapper(v, k)` (the third parameter, for table, is never passed)

Either the implementation should change, or the documentation.

**Comment by raiguard** [comment]
Thanks, I fixed some other places in `table` where the docs included that third parameter.
