### ISSUE TITLE
Documentation for table.find() mismatch

### ISSUE THREAD

**Issue by Majoca22** [raiguard/Factorio-Flib#36]
The current usage documentation for `table.find()` is:
```
local tbl = {"foo", "bar"}
local contains_foo = table.search(tbl, "foo") -- true
local contains_baz = table.search(tbl, "baz") -- false
```
which isn't demonstrating the `table.find()` function, and is instead using `table.search()` (which I don't see in the table module?)

**Comment by raiguard** [comment]
Sorry about that! Don't have doctests so sometimes these things slip through the cracks.

**Comment by Majoca22** [comment]
Thanks for addressing this! I'm still not sure the documentation is correct though; wouldn't `table.find(tbl, "foo")` return 1 (the key of foo) and `table.find(tbl, "baz")` return nil?

**Comment by raiguard** [comment]
Holy crud, I really dropped the ball on the docs for this function. Thanks!
