### ISSUE TITLE
Is it possible use flib in scenario with minimal changes?

### ISSUE THREAD

**Issue by kevinmama** [raiguard/Factorio-Flib#42]
I try to copy the whole project into my scenario. When starting scenario, there's a error in require function.
I'd like to run scenario without mod that more players like to join. So is there a way integrate flib into a scenario.

**Comment by raiguard** [comment]
Could you post the error? All requires in flib should be absolute, which should avoid this problem.

**Comment by kevinmama** [comment]
I figure it out. create a flib subdirectory, copy files, and replace all path that prefixed '\_\_filb\_\_/' with 'flib/'

factorio assume path prefixed with '\_\_fib\_\_' is a mod path. It can't be used in scenario.

**Comment by raiguard** [comment]
Ah, I see. I didn't think about that. Glad you figured it out!
