### ISSUE TITLE
Mod loading bugs

### ISSUE THREAD

**Issue by SimpleSirforever** [raiguard/Factorio-Flib#53]
### Description

Mod loading fails :Failed to load locale: Missing parameter values are found in __flib__/locale/zh-CN/flib.cfg:11..

**Comment by fuhaiwei** [comment]
0.12.7 has no bugs, 0.12.8 has bugs

**Comment by raiguard** [comment]
Something is going weird with the Crowdin script, I'll look into it.

**Comment by raiguard** [comment]
I haven't figured out the Crowdin script, but I'm pushing a hotfix for the issue right now to fix it temporarily.
