### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Jamiebear** [raiguard/Factorio-Flib#70]
Why does Factorio Library not work with Warptorio2?

**Comment by raiguard** [comment]
You will have to be more specific. What is "not working"?

**Comment by Jamiebear** [comment]
If you have Factorio Library on Warptorio2 just crashes would you know why that is?

**Comment by raiguard** [comment]
Crashes how? Please post the error message and attach `factorio-current.log`.

**Comment by Jamiebear** [comment]
![Screenshot (1398)](https://github.com/user-attachments/assets/1b1aba1f-b6dc-41ee-abda-e3fc93a341c1)

**Comment by Jamiebear** [comment]
Is that good or do you also need the log?

**Comment by raiguard** [comment]
This has nothing to do with flib, please report this to Warptorio2.

**Comment by Jamiebear** [comment]
If you remove your mod it works fine if you added your mod it crashs meaning your mod makes it crash.

**Comment by raiguard** [comment]
With just `flib` and `warptorio2` enabled, I can load the game just fine.

flib is a library mod, it doesn't do much on its own. Based on the screenshot you provided, it it crashing entirely within warptorio2.
